### ISSUE TITLE
[Propunere] JetBrains şi sculele lor

### ISSUE THREAD

**Issue by danpercic86** [ligaac/docs#1]
### Pe scurt, ce puncte dorești să fie atinse?
Cine-s JetBrains şi ce fac ei. Cum îmi activez o licenţă cu ajutorul GitHub Student Pack şi cum îmi instalez software-ul lor

### Dorești să scrii tu un articol pe tema asta?
Denisa Pap-Gherasim se ocupă deja.

**Comment by DenisaPG-11** [comment]
Aoloo, mi-ai greșit numele @danpercic86 :||||| :((

**Comment by danpercic86** [comment]
> Aoloo, mi-ai greșit numele @danpercic86 :||||| :((

Nu prea cred

**Comment by DenisaPG-11** [comment]
Haha, bună gluma :))
